// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdcczjwsrofvzuidllnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkY2N6andzcm9mdnp1aWRsbG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzY0MjYsImV4cCI6MjA1NzI1MjQyNn0.PTzDLzeCzZxJmlemui72Z7vmmo0m3T9jjjJvvpZuCt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);